set(_CATKIN_CURRENT_PACKAGE "rosbot_patrol")
set(rosbot_patrol_VERSION "0.0.0")
set(rosbot_patrol_MAINTAINER "adam <adam-krawczyk@outlook.com>")
set(rosbot_patrol_PACKAGE_FORMAT "2")
set(rosbot_patrol_BUILD_DEPENDS "roscpp" "rospy" "message_generation" "darknet_ros" "common_rosdeps")
set(rosbot_patrol_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "message_generation")
set(rosbot_patrol_BUILDTOOL_DEPENDS "catkin")
set(rosbot_patrol_BUILDTOOL_EXPORT_DEPENDS )
set(rosbot_patrol_EXEC_DEPENDS "roscpp" "rospy" "message_runtime" "common_rosdeps")
set(rosbot_patrol_RUN_DEPENDS "roscpp" "rospy" "message_runtime" "common_rosdeps" "message_generation")
set(rosbot_patrol_TEST_DEPENDS )
set(rosbot_patrol_DOC_DEPENDS )
set(rosbot_patrol_URL_WEBSITE "")
set(rosbot_patrol_URL_BUGTRACKER "")
set(rosbot_patrol_URL_REPOSITORY "")
set(rosbot_patrol_DEPRECATED "")